# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-file
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name generate-transcription
POST http://localhost:3333/videos/6b2368ff-1f35-4664-9d7f-6fca082d9112/transcription
Content-Type: application/json

{
    "prompt": "clean architecture, add"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "6b2368ff-1f35-4664-9d7f-6fca082d9112",
    "temperature": 0.9,
    "template": "Conte uma nova piada que continue a história do pintinho a seguir: '''{transcription}'''"
}